export const code: jsonDataType[] = [
    { name: '条形码生成器', path: '/code/bar-code-generator' },
    { name: '条形码扫描', path: '/code/bar-code-scanner' },
    { name: 'Base32 解码', path: '/code/base32-decode' },
    { name: 'Base32 编码', path: '/code/base32-encode' },
    { name: 'Base58 解码', path: '/code/base58-decode' },
    { name: 'Base58 编码', path: '/code/base58-encode' },
    { name: 'Base62 解码', path: '/code/base62-decode' },
    { name: 'Base62 编码', path: '/code/base62-encode' },
    { name: 'Base64 解码', path: '/code/base64-decode' },
    { name: 'Base64 编码', path: '/code/base64-encode' },
    { name: 'Base64 解码文件', path: '/code/base64-file-decode' },
    { name: 'Base64 编码文件', path: '/code/base64-file-encode' },
    { name: 'Base64 转 Hex', path: '/code/base64-to-hex' },
    { name: 'Base85 解码', path: '/code/base85-decode' },
    { name: 'Base85 编码', path: '/code/base85-encode' },
    { name: 'Base91 解码', path: '/code/base91-decode' },
    { name: 'Base91 编码', path: '/code/base91-encode' },
    { name: 'GZip 解码', path: '/code/gzip-decode' },
    { name: 'GZip 编码', path: '/code/gzip-encode' },
    { name: 'Hex 解码', path: '/code/hex-decode' },
    { name: 'Hex 编码', path: '/code/hex-encode' },
    { name: 'Hex 转 Base64', path: '/code/hex-to-base64' },
    { name: '转换文本文件编码格式', path: '/code/iconv' },
    { name: 'IDN 解码', path: '/code/idn-decode' },
    { name: 'IDN 编码', path: '/code/idn-encode' },
    { name: '摩斯密码 解码', path: '/code/morse-decode' },
    { name: '摩斯密码 编码', path: '/code/morse-encode' },
    { name: '为电子邮件生成二维码', path: '/code/qr-code-gen-for-email' },
    { name: '为以太坊地址生成二维码', path: '/code/qr-code-gen-for-eth' },
    { name: '为电话号码生成二维码', path: '/code/qr-code-gen-for-phone' },
    { name: '为短信生成二维码', path: '/code/qr-code-gen-for-sms' },
    { name: '为文本生成二维码', path: '/code/qr-code-gen-for-text' },
    { name: '为 URL 生成二维码', path: '/code/qr-code-gen-for-url' },
    { name: '二维码扫描', path: '/code/qr-code-scanner' },
    { name: 'UTF7 解码', path: '/code/utf7-decode' },
    { name: 'Unicode 解码', path: '/code/unicode-decode' },
    { name: 'Unicode 编码', path: '/code/unicode-encode' },
    { name: 'URL 解码', path: '/code/url-decode' },
    { name: 'URL 编码', path: '/code/url-encode' },
    { name: 'UTF16 解码', path: '/code/utf16-decode' },
    { name: 'UTF16 编码', path: '/code/utf16-encode' },
    { name: 'UTF32 解码', path: '/code/utf32-decode' },
    { name: 'UTF32 编码', path: '/code/utf32-encode' },
    { name: 'UTF7 编码', path: '/code/utf7-encode' },
    { name: 'UTF8 解码', path: '/code/utf8-decode' },
    { name: 'UTF8 编码', path: '/code/utf8-encode' },
    { name: 'Toml 转 Properties', path: '/code/toml-to-properties' },
    { name: 'Properties 转 Toml', path: '/code/properties-to-toml' },
];
