export const programming: jsonDataType[] = [
    { name: '数字进制转换', path: '/Programming/base-conversion' },
    { name: 'Chmod 计算器', path: '/Programming/chmod-calculator' },
    { name: '代码转图片', path: '/Programming/code-to-image' },
    { name: 'CSS边框圆角生成器', path: '/Programming/css-border-radius-generator' },
    { name: 'CSS 线性渐变色生成器', path: '/Programming/css-linear-gradient-generator' },
    { name: 'Curl 转代码', path: '/Programming/curl-to-code' },
    { name: 'Java 转义', path: '/Programming/java-escape' },
    { name: 'Java 反转义', path: '/Programming/java-unescape' },
    { name: 'JavaScript 转义', path: '/Programming/js-escape' },
    { name: 'Javascript 按键事件码表', path: '/Programming/js-key-code' },
    { name: '正则编辑器', path: '/Programming/js-regex-tester' },
    { name: 'JavaScript 反转义', path: '/Programming/js-unescape' },
    { name: 'JWT 生成器', path: '/Programming/jwt-generator' },
    { name: 'JWT 解析器', path: '/Programming/jwt-parse' },
    { name: 'Paseto 生成器', path: '/Programming/paseto-generator' },
    { name: 'Paseto 解析器', path: '/Programming/paseto-parse' },
    { name: '原码反码补码计算器', path: '/Programming/source-complement-anticode-calculator' },
    { name: 'SQL 转义', path: '/Programming/sql-escape' },
    { name: 'SQL 压缩', path: '/Programming/sql-minify' },
    { name: 'SQL 格式化', path: '/Programming/sql-pretty' },
    { name: 'SQL 反转义', path: '/Programming/sql-unescape' },
    { name: '单位转换', path: '/Programming/unit-conversion' },
    { name: 'URL 解析器', path: '/Programming/url-parse' },
    { name: 'UTM 生成器', path: '/Programming/utm-generator' },
    { name: 'UUID 解析器', path: '/Programming/uuid-parser' },
    { name: 'UUID/ULID 生成器', path: '/Programming/uuid-ulid-generator' },
    { name: 'XML路径', path: '/Programming/x-path' },
    { name: 'XML 转义', path: '/Programming/xml-escape' },
    { name: 'XML 反转义', path: '/Programming/xml-unescape' },
    { name: 'XML 压缩', path: '/Programming/xml-minify' },
    { name: 'XML 格式化', path: '/Programming/xml-prettify' },
    { name: 'HTML 转义', path: '/Programming/html-escape' },
    { name: 'HTML 反转义', path: '/Programming/html-unescape' },
    { name: 'HTML 压缩', path: '/Programming/html-minify' },
    { name: 'HTML 格式化', path: '/Programming/html-prettify' },
    { name: 'CSS 压缩', path: '/Programming/css-minify' },
    { name: 'CSS 格式化', path: '/Programming/css-prettify' },
    { name: 'JavaScript 压缩', path: '/Programming/javascript-minify' },
    { name: 'JavaScript 格式化', path: '/Programming/javascript-prettify' },
    { name: 'SQL Schema 转 JAVA Bean', path: '/Programming/sql-schema-to-java-bean' },
    { name: 'SQL Schema 转 GO Struct', path: '/Programming/sql-schema-to-go-struct' },
    { name: 'SQL Schema 转 Python Class', path: '/Programming/sql-schema-to-python-class' },
    { name: 'SQL Schema 转 Ruby Module', path: '/Programming/sql-schema-to-ruby-module' },
    { name: 'SQL Schema 转 Rust Struct', path: '/Programming/sql-schema-to-rust-struct' },
    { name: 'SQL Schema 转 C# Class', path: '/Programming/sql-schema-to-c-0-class' },
    { name: 'SQL Schema 转 C++ Struct', path: '/Programming/sql-schema-to-c-00-struct' },
    { name: 'SQL Schema 转 Swift Struct', path: '/Programming/sql-schema-to-swift-struct' },
    {
        name: 'SQL Schema 转 Objective-C Interface',
        path: '/Programming/sql-schema-to-objective-c-interface',
    },
    {
        name: 'SQL Schema 转 TypeScript Interface',
        path: '/Programming/sql-schema-to-typescript-interface',
    },
    { name: 'SQL Schema 转 IO-TS', path: '/Programming/sql-schema-to-io-ts' },
];
