export const text = [
    { name: 'ASCII 码对照表', path: '/text/ascii' },
    { name: '变量命名转换', path: '/text/case-converter' },
    { name: '文本提取器', path: '/text/extractor' },
    { name: 'Figlet', path: '/text/figlet' },
    { name: '公式计算', path: '/text/formula-parser' },
    { name: '随机假文生成器', path: '/text/lorem-ipsum-generator' },
    { name: 'Markdown 预览', path: '/text/markdown-preview' },
    { name: '八进制/十六进制转Unicode', path: '/text/octal-or-hex-to-unicode' },
    { name: '密码生成器', path: '/text/password' },
    { name: '随机字符串生成器', path: '/text/random-string' },
    { name: 'Slug 生成器', path: '/text/slug-generator' },
    { name: '字符串转义', path: '/text/string-escape' },
    { name: '文本分隔', path: '/text/string-split' },
    { name: '字符串反转义', path: '/text/string-unescape' },
    { name: '文本分析', path: '/text/text-analyzer' },
    { name: '文本去重', path: '/text/text-deduplication' },
    { name: '文本 对比', path: '/text/text-diff' },
    { name: '文本排序', path: '/text/text-sort' },
    { name: 'CSV 转 TSV', path: '/text/table-csv-to-tsv' },
    { name: 'CSV 转 Markdown', path: '/text/table-csv-to-markdown' },
    { name: 'CSV 转 HTML', path: '/text/table-csv-to-html' },
    { name: 'CSV 转 JSON', path: '/text/table-csv-to-json' },
    { name: 'CSV 转 SQL', path: '/text/table-csv-to-sql' },
    { name: 'TSV 转 CSV', path: '/text/table-tsv-to-csv' },
    { name: 'TSV 转 Markdown', path: '/text/table-tsv-to-markdown' },
    { name: 'TSV 转 HTML', path: '/text/table-tsv-to-html' },
    { name: 'TSV 转 JSON', path: '/text/table-tsv-to-json' },
    { name: 'TSV 转 SQL', path: '/text/table-tsv-to-sql' },
    { name: 'Markdown 转 TSV', path: '/text/table-markdown-to-tsv' },
    { name: 'Markdown 转 CSV', path: '/text/table-markdown-to-csv' },
    { name: 'Markdown 转 HTML', path: '/text/table-markdown-to-html' },
    { name: 'Markdown 转 JSON', path: '/text/table-markdown-to-json' },
    { name: 'Markdown 转 SQL', path: '/text/table-markdown-to-sql' },
    { name: 'HTML 转 TSV', path: '/text/table-html-to-tsv' },
    { name: 'HTML 转 Markdown', path: '/text/table-html-to-markdown' },
    { name: 'HTML 转 CSV', path: '/text/table-html-to-csv' },
    { name: 'HTML 转 JSON', path: '/text/table-html-to-json' },
    { name: 'HTML 转 SQL', path: '/text/table-html-to-sql' },
    { name: 'JSON 转 TSV', path: '/text/table-json-to-tsv' },
    { name: 'JSON 转 Markdown', path: '/text/table-json-to-markdown' },
    { name: 'JSON 转 HTML', path: '/text/table-json-to-html' },
    { name: 'JSON 转 CSV', path: '/text/table-json-to-csv' },
    { name: 'JSON 转 SQL', path: '/text/table-json-to-sql' },
    { name: 'SQL 转 TSV', path: '/text/table-sql-to-tsv' },
    { name: 'SQL 转 Markdown', path: '/text/table-sql-to-markdown' },
    { name: 'SQL 转 HTML', path: '/text/table-sql-to-html' },
    { name: 'SQL 转 JSON', path: '/text/table-sql-to-json' },
    { name: 'SQL 转 CSV', path: '/text/table-sql-to-csv' },
];
